language: python

install:
    - "pip install -r requirements.txt"
    - "wget 'http://pandas.pydata.org/pandas-docs/version/0.15.1/pandas.zip'"
    - "unzip pandas.zip"
    - "doc2dash -n Pandas html"

script:
    - "tar czvf Pandas.docset.tgz Pandas.docset"
